#include <EGL/egl.h>
#include "../../macros.h"

/* EGL10 - Errors - eglGetError
 * Covered requirement: GS-EGL10-ER-GE-014
 * Native pixmap creation and invalid-handle detection are platform-specific.
 */
static const char* test_case = "GS_EGL10_ER_GE_TC_014";
static const char* test_procedure = "GS_EGL10_ER_GE_TP_014";

#ifdef GS_EGL_PLATFORM_TEST_HOOKS
static EGLBoolean fixture_prepared = EGL_FALSE;
static EGLDisplay display = EGL_NO_DISPLAY;
static EGLSurface created_surface = EGL_NO_SURFACE;
extern EGLBoolean GS_EGL10_prepare_invalid_native_pixmap(
    EGLDisplay *display, EGLConfig *config, EGLNativePixmapType *pixmap);
extern void GS_EGL10_cleanup_invalid_native_pixmap(void);
#endif

void GS_EGL10_ER_GE_TP_014_init(void)
{
#ifdef GS_EGL_PLATFORM_TEST_HOOKS
    EGLConfig config = (EGLConfig)0;
    EGLNativePixmapType pixmap = (EGLNativePixmapType)0;
    EGLint error;

    fixture_prepared = GS_EGL10_prepare_invalid_native_pixmap(
        &display, &config, &pixmap);
    if (!fixture_prepared)
    {
        TEST_LOG_FAIL(test_case, test_procedure,
            "Invalid native-pixmap setup failed");
        return;
    }

    /* The hook supplies a handle which the target EGL implementation can
     * detect as an invalid native pixmap. eglGetError must retrieve the error
     * generated by eglCreatePixmapSurface in this calling thread.
     */
    (void)eglGetError();
    created_surface = eglCreatePixmapSurface(display, config, pixmap, NULL);
    error = eglGetError();

    if (created_surface != EGL_NO_SURFACE || error != EGL_BAD_NATIVE_PIXMAP)
    {
        TEST_LOG_FAIL(test_case, test_procedure,
            "Expected EGL_NO_SURFACE/EGL_BAD_NATIVE_PIXMAP, got %p/0x%x",
            (void*)created_surface, error);
        return;
    }

    TEST_LOG_SUCCESS(test_case, test_procedure);
#else
    TEST_LOG_INFO("[ %s ][ %s ] Not applicable: GS_EGL_PLATFORM_TEST_HOOKS is not enabled.",
        test_case, test_procedure);
#endif
}

void GS_EGL10_ER_GE_TP_014_draw(void) { }

void GS_EGL10_ER_GE_TP_014_close(void)
{
#ifdef GS_EGL_PLATFORM_TEST_HOOKS
    if (created_surface != EGL_NO_SURFACE && display != EGL_NO_DISPLAY)
        (void)eglDestroySurface(display, created_surface);
    if (fixture_prepared)
        GS_EGL10_cleanup_invalid_native_pixmap();
#endif
}
