#include <EGL/egl.h>
#include "../../helpers.h"

/* EGL10 - Errors - eglGetError
 * Covered requirement: GS-EGL10-ER-GE-015
 * Native window creation and invalid-handle detection are platform-specific.
 */
static const char* test_case = "GS_EGL10_ER_GE_TC_015";
static const char* test_procedure = "GS_EGL10_ER_GE_TP_015";

#ifdef GS_EGL_PLATFORM_TEST_HOOKS
static EGLBoolean fixture_prepared = EGL_FALSE;
static EGLDisplay display = EGL_NO_DISPLAY;
static EGLSurface created_surface = EGL_NO_SURFACE;
#endif

void GS_EGL10_ER_GE_TP_015_init(void)
{
#ifdef GS_EGL_PLATFORM_TEST_HOOKS
    EGLConfig config = (EGLConfig)0;
    EGLNativeWindowType window = (EGLNativeWindowType)0;
    EGLint error;

    fixture_prepared = GS_EGL10_prepare_invalid_native_window(
        &display, &config, &window);
    if (!fixture_prepared)
    {
        TEST_LOG_FAIL(test_case, test_procedure,
            "Invalid native-window setup failed");
        return;
    }

    /* The hook supplies a handle which the target EGL implementation can
     * detect as an invalid native window. eglGetError must retrieve the error
     * generated by eglCreateWindowSurface in this calling thread.
     */
    (void)eglGetError();
    created_surface = eglCreateWindowSurface(display, config, window, NULL);
    error = eglGetError();

    if (created_surface != EGL_NO_SURFACE || error != EGL_BAD_NATIVE_WINDOW)
    {
        TEST_LOG_FAIL(test_case, test_procedure,
            "Expected EGL_NO_SURFACE/EGL_BAD_NATIVE_WINDOW, got %p/0x%x",
            (void*)created_surface, error);
        return;
    }

    TEST_LOG_SUCCESS(test_case, test_procedure);
#else
    TEST_LOG_INFO("[ %s ][ %s ] Not applicable: GS_EGL_PLATFORM_TEST_HOOKS is not enabled.",
        test_case, test_procedure);
#endif
}

void GS_EGL10_ER_GE_TP_015_draw(void) { }

void GS_EGL10_ER_GE_TP_015_close(void)
{
#ifdef GS_EGL_PLATFORM_TEST_HOOKS
    if (created_surface != EGL_NO_SURFACE && display != EGL_NO_DISPLAY)
        (void)eglDestroySurface(display, created_surface);
    if (fixture_prepared)
        GS_EGL10_cleanup_invalid_native_window();
#endif
}
