#include <glad/glad.h>
#include <stdint.h>
#include <stdio.h>

/*
 * OpenGL ES 3.1 / GLSL ES 3.10
 *
 * Scenario examples for:
 *     glBindBufferBase(target, index, buffer)
 *
 * A valid OpenGL ES 3.1 context must be current before running
 * these scenarios.
 */

static const char *bind_error_name(GLenum error)
{
    switch (error) {
    case GL_NO_ERROR:          return "GL_NO_ERROR";
    case GL_INVALID_ENUM:      return "GL_INVALID_ENUM";
    case GL_INVALID_VALUE:     return "GL_INVALID_VALUE";
    case GL_INVALID_OPERATION: return "GL_INVALID_OPERATION";
    case GL_OUT_OF_MEMORY:     return "GL_OUT_OF_MEMORY";
    default:                   return "UNKNOWN_GL_ERROR";
    }
}

static void clear_bind_errors(void)
{
    while (glGetError() != GL_NO_ERROR) {
    }
}

static GLuint create_ssbo_with_data(void)
{
    static const GLuint data[] = { 1u, 2u, 3u, 4u };
    GLuint buffer = 0;

    glGenBuffers(1, &buffer);
    glBindBuffer(GL_SHADER_STORAGE_BUFFER, buffer);
    glBufferData(GL_SHADER_STORAGE_BUFFER, sizeof(data), data, GL_DYNAMIC_COPY);

    return buffer;
}

/*
 * Scenario 1
 *
 * Bind a populated SSBO to binding point zero and query the
 * indexed binding point afterwards.
 */
void scenario_bind_buffer_base_valid_ssbo(void)
{
    GLint bound_buffer = 0;
    GLuint buffer = create_ssbo_with_data();

    clear_bind_errors();
    glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 0, buffer);
    GLenum error = glGetError();

    glGetIntegeri_v(GL_SHADER_STORAGE_BUFFER_BINDING, 0, &bound_buffer);

    printf("Scenario 1 - Valid SSBO binding\n");
    printf("  Expected error : GL_NO_ERROR\n");
    printf("  Actual error   : %s\n", bind_error_name(error));
    printf("  Binding point  : 0\n");
    printf("  Expected buffer: %u\n", buffer);
    printf("  Actual buffer  : %d\n\n", bound_buffer);

    glDeleteBuffers(1, &buffer);
}

/*
 * Scenario 2
 *
 * Bind buffer name zero to remove the current binding from the
 * selected indexed binding point and the general binding point.
 */
void scenario_bind_buffer_base_unbind(void)
{
    GLint bound_buffer = -1;
    GLuint buffer = create_ssbo_with_data();

    glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 0, buffer);

    clear_bind_errors();
    glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 0, 0);
    GLenum error = glGetError();

    glGetIntegeri_v(GL_SHADER_STORAGE_BUFFER_BINDING, 0, &bound_buffer);

    printf("Scenario 2 - Unbind with buffer == 0\n");
    printf("  Expected error : GL_NO_ERROR\n");
    printf("  Actual error   : %s\n", bind_error_name(error));
    printf("  Expected buffer: 0\n");
    printf("  Actual buffer  : %d\n\n", bound_buffer);

    glDeleteBuffers(1, &buffer);
}

/*
 * Scenario 3
 *
 * A name generated by glGenBuffers has no buffer object state
 * until its first bind. glBindBufferBase performs that first bind.
 */
void scenario_bind_buffer_base_first_bind_creates_state(void)
{
    GLuint buffer = 0;
    GLboolean before;
    GLboolean after;

    glGenBuffers(1, &buffer);
    before = glIsBuffer(buffer);

    clear_bind_errors();
    glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 0, buffer);
    GLenum error = glGetError();

    after = glIsBuffer(buffer);

    printf("Scenario 3 - First bind creates buffer state\n");
    printf("  Buffer name before bind is object: %s\n", before ? "YES" : "NO");
    printf("  Expected error                    : GL_NO_ERROR\n");
    printf("  Actual error                      : %s\n", bind_error_name(error));
    printf("  Buffer name after bind is object  : %s\n\n", after ? "YES" : "NO");

    glDeleteBuffers(1, &buffer);
}

/*
 * Scenario 4
 *
 * Bind at the highest valid SSBO binding point. The implementation
 * limit is queried rather than assumed.
 */
void scenario_bind_buffer_base_highest_valid_index(void)
{
    GLint count = 0;
    GLuint buffer;

    glGetIntegerv(GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS, &count);

    printf("Scenario 4 - Highest valid SSBO binding point\n");
    printf("  Reported binding-point count: %d\n", count);

    if (count <= 0) {
        printf("  SKIPPED: no usable SSBO binding point was reported.\n\n");
        return;
    }

    buffer = create_ssbo_with_data();

    clear_bind_errors();
    glBindBufferBase(
        GL_SHADER_STORAGE_BUFFER,
        (GLuint)(count - 1),
        buffer
    );
    GLenum error = glGetError();

    printf("  Requested index : %d\n", count - 1);
    printf("  Expected error  : GL_NO_ERROR\n");
    printf("  Actual error    : %s\n\n", bind_error_name(error));

    glDeleteBuffers(1, &buffer);
}

/*
 * Scenario 5
 *
 * index == limit is outside the valid indexed binding-point range.
 *
 * Expected error:
 *     GL_INVALID_VALUE
 */
void scenario_bind_buffer_base_index_out_of_range(void)
{
    GLint count = 0;
    GLuint buffer = create_ssbo_with_data();

    glGetIntegerv(GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS, &count);

    clear_bind_errors();
    glBindBufferBase(
        GL_SHADER_STORAGE_BUFFER,
        (GLuint)count,
        buffer
    );
    GLenum error = glGetError();

    printf("Scenario 5 - SSBO index outside supported range\n");
    printf("  Requested index : %d\n", count);
    printf("  Expected error  : GL_INVALID_VALUE\n");
    printf("  Actual error    : %s\n\n", bind_error_name(error));

    glDeleteBuffers(1, &buffer);
}

/*
 * Scenario 6
 *
 * GL_ARRAY_BUFFER is a buffer target, but it is not an indexed
 * target accepted by glBindBufferBase.
 *
 * Expected error:
 *     GL_INVALID_ENUM
 */
void scenario_bind_buffer_base_invalid_target(void)
{
    GLuint buffer = create_ssbo_with_data();

    clear_bind_errors();
    glBindBufferBase(GL_ARRAY_BUFFER, 0, buffer);
    GLenum error = glGetError();

    printf("Scenario 6 - Target without indexed binding points\n");
    printf("  Target          : GL_ARRAY_BUFFER\n");
    printf("  Expected error  : GL_INVALID_ENUM\n");
    printf("  Actual error    : %s\n\n", bind_error_name(error));

    glDeleteBuffers(1, &buffer);
}

void run_all_bind_buffer_base_scenarios(void)
{
    printf("\n===============================================\n");
    printf("glBindBufferBase() Scenario Demonstration\n");
    printf("OpenGL ES 3.1 / GLSL ES 3.10\n");
    printf("===============================================\n\n");

    scenario_bind_buffer_base_valid_ssbo();
    scenario_bind_buffer_base_unbind();
    scenario_bind_buffer_base_first_bind_creates_state();
    scenario_bind_buffer_base_highest_valid_index();
    scenario_bind_buffer_base_index_out_of_range();
    scenario_bind_buffer_base_invalid_target();

    printf("===============================================\n");
    printf("Scenario demonstration completed.\n");
    printf("===============================================\n");
}
