#include <glad/glad.h>
#include <stdio.h>
#include <stdint.h>

/*
 * OpenGL ES 3.1 / GLSL ES 3.10
 *
 * Scenario examples for:
 *     glDispatchCompute(num_groups_x,
 *                       num_groups_y,
 *                       num_groups_z)
 *
 * This file demonstrates the behavior described in the
 * glDispatchCompute documentation.
 *
 * IMPORTANT:
 * A valid OpenGL ES 3.1 context must be current before
 * running these scenarios.
 *
 * Scenarios 1-9 assume that a valid GLSL ES 3.10 compute
 * shader program is currently active.
 */


/* ============================================================
 * GL ERROR NAME
 * ============================================================ */

static const char *gl_error_name(GLenum error)
{
    switch (error)
    {
        case GL_NO_ERROR:
            return "GL_NO_ERROR";

        case GL_INVALID_ENUM:
            return "GL_INVALID_ENUM";

        case GL_INVALID_VALUE:
            return "GL_INVALID_VALUE";

        case GL_INVALID_OPERATION:
            return "GL_INVALID_OPERATION";

        case GL_OUT_OF_MEMORY:
            return "GL_OUT_OF_MEMORY";

        default:
            return "UNKNOWN_GL_ERROR";
    }
}


/* ============================================================
 * CLEAR PREVIOUS GL ERRORS
 * ============================================================ */

static void clear_gl_errors(void)
{
    while (glGetError() != GL_NO_ERROR)
    {
        /* Clear previous errors. */
    }
}


/* ============================================================
 * DISPATCH HELPER
 * ============================================================ */

static void run_dispatch_scenario(
        const char *name,
        GLuint num_groups_x,
        GLuint num_groups_y,
        GLuint num_groups_z)
{
    GLenum error;

    /*
     * Remove errors generated by previous OpenGL ES calls.
     */
    clear_gl_errors();

    /*
     * Execute glDispatchCompute().
     */
    glDispatchCompute(
        num_groups_x,
        num_groups_y,
        num_groups_z
    );

    /*
     * Check the result of the dispatch call.
     */
    error = glGetError();

    printf(
        "%s\n",
        name
    );

    printf(
        "  Dispatch groups : (%u, %u, %u)\n",
        num_groups_x,
        num_groups_y,
        num_groups_z
    );

    printf(
        "  GL error        : %s\n",
        gl_error_name(error)
    );

    printf("\n");
}


/* ============================================================
 * SCENARIO 1
 *
 * Normal 1D dispatch
 *
 * Dispatches:
 *
 *     64 x 1 x 1 work groups
 *
 * This is a basic valid usage example.
 * ============================================================ */

void scenario_dispatch_normal_1d(void)
{
    run_dispatch_scenario(
        "Scenario 1 - Normal 1D dispatch",
        64,
        1,
        1
    );
}


/* ============================================================
 * SCENARIO 2
 *
 * Normal 2D dispatch
 *
 * Dispatches:
 *
 *     16 x 16 x 1 work groups
 *
 * Demonstrates that the dispatch grid can use two dimensions.
 * ============================================================ */

void scenario_dispatch_normal_2d(void)
{
    run_dispatch_scenario(
        "Scenario 2 - Normal 2D dispatch",
        16,
        16,
        1
    );
}


/* ============================================================
 * SCENARIO 3
 *
 * Normal 3D dispatch
 *
 * Dispatches:
 *
 *     4 x 4 x 4 work groups
 *
 * Demonstrates the complete three-dimensional dispatch grid.
 * ============================================================ */

void scenario_dispatch_normal_3d(void)
{
    run_dispatch_scenario(
        "Scenario 3 - Normal 3D dispatch",
        4,
        4,
        4
    );
}


/* ============================================================
 * SCENARIO 4
 *
 * Zero work groups in X.
 *
 * According to OpenGL ES 3.1, if any dispatch dimension is
 * zero, no work groups are launched.
 *
 * The call itself does not generate an error.
 * ============================================================ */

void scenario_dispatch_zero_groups_x(void)
{
    run_dispatch_scenario(
        "Scenario 4 - Zero work groups in X",
        0,
        1,
        1
    );
}


/* ============================================================
 * SCENARIO 5
 *
 * Zero work groups in Y.
 *
 * No work groups are launched.
 * ============================================================ */

void scenario_dispatch_zero_groups_y(void)
{
    run_dispatch_scenario(
        "Scenario 5 - Zero work groups in Y",
        1,
        0,
        1
    );
}


/* ============================================================
 * SCENARIO 6
 *
 * Zero work groups in Z.
 *
 * No work groups are launched.
 * ============================================================ */

void scenario_dispatch_zero_groups_z(void)
{
    run_dispatch_scenario(
        "Scenario 6 - Zero work groups in Z",
        1,
        1,
        0
    );
}


/* ============================================================
 * SCENARIO 7
 *
 * Query the implementation limit for X and demonstrate a
 * dispatch that exceeds the maximum.
 *
 * GL_MAX_COMPUTE_WORK_GROUP_COUNT is queried with index 0
 * for the X dimension.
 *
 * Expected error:
 *
 *     GL_INVALID_VALUE
 * ============================================================ */

void scenario_dispatch_exceed_max_x(void)
{
    GLint max_x = 0;

    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_COUNT,
        0,
        &max_x
    );

    printf(
        "Scenario 7 - Maximum X work-group count: %d\n",
        max_x
    );

    if (max_x < 0)
    {
        printf(
            "Unable to obtain a valid X work-group limit.\n\n"
        );
        return;
    }

    clear_gl_errors();

    glDispatchCompute(
        (GLuint)max_x + 1u,
        1,
        1
    );

    GLenum error = glGetError();

    printf(
        "  Dispatch groups : (%u, 1, 1)\n",
        (GLuint)max_x + 1u
    );

    printf(
        "  Expected error   : GL_INVALID_VALUE\n"
    );

    printf(
        "  Actual error     : %s\n\n",
        gl_error_name(error)
    );
}


/* ============================================================
 * SCENARIO 8
 *
 * Query the implementation limit for Y and demonstrate a
 * dispatch that exceeds the maximum.
 *
 * Expected error:
 *
 *     GL_INVALID_VALUE
 * ============================================================ */

void scenario_dispatch_exceed_max_y(void)
{
    GLint max_y = 0;

    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_COUNT,
        1,
        &max_y
    );

    printf(
        "Scenario 8 - Maximum Y work-group count: %d\n",
        max_y
    );

    if (max_y < 0)
    {
        printf(
            "Unable to obtain a valid Y work-group limit.\n\n"
        );
        return;
    }

    clear_gl_errors();

    glDispatchCompute(
        1,
        (GLuint)max_y + 1u,
        1
    );

    GLenum error = glGetError();

    printf(
        "  Dispatch groups : (1, %u, 1)\n",
        (GLuint)max_y + 1u
    );

    printf(
        "  Expected error   : GL_INVALID_VALUE\n"
    );

    printf(
        "  Actual error     : %s\n\n",
        gl_error_name(error)
    );
}


/* ============================================================
 * SCENARIO 9
 *
 * Query the implementation limit for Z and demonstrate a
 * dispatch that exceeds the maximum.
 *
 * Expected error:
 *
 *     GL_INVALID_VALUE
 * ============================================================ */

void scenario_dispatch_exceed_max_z(void)
{
    GLint max_z = 0;

    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_COUNT,
        2,
        &max_z
    );

    printf(
        "Scenario 9 - Maximum Z work-group count: %d\n",
        max_z
    );

    if (max_z < 0)
    {
        printf(
            "Unable to obtain a valid Z work-group limit.\n\n"
        );
        return;
    }

    clear_gl_errors();

    glDispatchCompute(
        1,
        1,
        (GLuint)max_z + 1u
    );

    GLenum error = glGetError();

    printf(
        "  Dispatch groups : (1, 1, %u)\n",
        (GLuint)max_z + 1u
    );

    printf(
        "  Expected error   : GL_INVALID_VALUE\n"
    );

    printf(
        "  Actual error     : %s\n\n",
        gl_error_name(error)
    );
}


/* ============================================================
 * SCENARIO 10
 *
 * No active compute shader executable.
 *
 * The current program and any active program pipeline are
 * removed before glDispatchCompute() is called.
 *
 * Expected error:
 *
 *     GL_INVALID_OPERATION
 * ============================================================ */

void scenario_dispatch_no_active_program(void)
{
    /*
     * Remove the current program.
     */
    glUseProgram(0);

    /*
     * Make sure that no program pipeline is active.
     */
    glBindProgramPipeline(0);

    clear_gl_errors();

    glDispatchCompute(
        1,
        1,
        1
    );

    GLenum error = glGetError();

    printf(
        "Scenario 10 - No active compute shader executable\n"
    );

    printf(
        "  Dispatch groups : (1, 1, 1)\n"
    );

    printf(
        "  Expected error   : GL_INVALID_OPERATION\n"
    );

    printf(
        "  Actual error     : %s\n\n",
        gl_error_name(error)
    );
}


/* ============================================================
 * SCENARIO 11
 *
 * Active linked program without a compute shader executable.
 *
 * The supplied program must be a successfully linked graphics
 * program containing graphics shader stages but no compute
 * shader stage.
 *
 * Expected error:
 *
 *     GL_INVALID_OPERATION
 * ============================================================ */

void scenario_dispatch_graphics_program_active(
        GLuint graphics_program)
{
    /*
     * Activate the graphics-only program.
     */
    glUseProgram(graphics_program);

    clear_gl_errors();

    glDispatchCompute(
        1,
        1,
        1
    );

    GLenum error = glGetError();

    printf(
        "Scenario 11 - Graphics-only program active\n"
    );

    printf(
        "  Dispatch groups : (1, 1, 1)\n"
    );

    printf(
        "  Expected error   : GL_INVALID_OPERATION\n"
    );

    printf(
        "  Actual error     : %s\n\n",
        gl_error_name(error)
    );
}


/* ============================================================
 * SCENARIO 12
 *
 * Print compute-related implementation limits.
 *
 * This scenario is useful for observing the relationship
 * between:
 *
 *     Work-group count
 *     Work-group size
 *     Total local invocations
 *
 * ============================================================ */

void scenario_print_compute_limits(void)
{
    GLint max_count_x = 0;
    GLint max_count_y = 0;
    GLint max_count_z = 0;

    GLint max_size_x = 0;
    GLint max_size_y = 0;
    GLint max_size_z = 0;

    GLint max_invocations = 0;


    /*
     * Maximum number of work groups that can be dispatched
     * in each dimension.
     */
    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_COUNT,
        0,
        &max_count_x
    );

    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_COUNT,
        1,
        &max_count_y
    );

    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_COUNT,
        2,
        &max_count_z
    );


    /*
     * Maximum local work-group size in each dimension.
     */
    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_SIZE,
        0,
        &max_size_x
    );

    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_SIZE,
        1,
        &max_size_y
    );

    glGetIntegeri_v(
        GL_MAX_COMPUTE_WORK_GROUP_SIZE,
        2,
        &max_size_z
    );


    /*
     * Maximum number of local invocations in one work group.
     */
    glGetIntegerv(
        GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS,
        &max_invocations
    );


    printf(
        "Scenario 12 - Compute implementation limits\n"
    );

    printf(
        "  MAX_COMPUTE_WORK_GROUP_COUNT      : "
        "(%d, %d, %d)\n",
        max_count_x,
        max_count_y,
        max_count_z
    );

    printf(
        "  MAX_COMPUTE_WORK_GROUP_SIZE       : "
        "(%d, %d, %d)\n",
        max_size_x,
        max_size_y,
        max_size_z
    );

    printf(
        "  MAX_COMPUTE_WORK_GROUP_INVOCATIONS: %d\n\n",
        max_invocations
    );
}


/* ============================================================
 * RUN ALL SCENARIOS
 *
 * This function is only a convenience function for the
 * scenario demonstration.
 *
 * Scenarios 1-9 require a valid active compute shader program.
 *
 * Scenario 10 intentionally removes the active program.
 *
 * Scenario 11 requires a valid graphics-only program.
 * ============================================================ */

void run_all_dispatch_scenarios(GLuint graphics_program)
{
    printf(
        "\n"
        "===============================================\n"
        "glDispatchCompute() Scenario Demonstration\n"
        "OpenGL ES 3.1 / GLSL ES 3.10\n"
        "===============================================\n\n"
    );


    /*
     * Display implementation-dependent limits first.
     */
    scenario_print_compute_limits();


    /*
     * Valid dispatch examples.
     */
    scenario_dispatch_normal_1d();

    scenario_dispatch_normal_2d();

    scenario_dispatch_normal_3d();


    /*
     * Zero work-group examples.
     */
    scenario_dispatch_zero_groups_x();

    scenario_dispatch_zero_groups_y();

    scenario_dispatch_zero_groups_z();


    /*
     * Maximum work-group count examples.
     */
    scenario_dispatch_exceed_max_x();

    scenario_dispatch_exceed_max_y();

    scenario_dispatch_exceed_max_z();


    /*
     * No active program.
     */
    scenario_dispatch_no_active_program();


    /*
     * Graphics-only program.
     */
    if (graphics_program != 0)
    {
        scenario_dispatch_graphics_program_active(
            graphics_program
        );
    }
    else
    {
        printf(
            "Scenario 11 - Graphics-only program active: SKIPPED\n"
            "Reason: graphics_program == 0\n\n"
        );
    }


    printf(
        "===============================================\n"
        "Scenario demonstration completed.\n"
        "===============================================\n"
    );
}
