TEST_PROCEDURE(GS_GLES31_CS_BD_TP_001, DEFAULT_TEST_RUN_TIME, "GLES31", "ComputeShader", "glBufferData")
TEST_PROCEDURE(GS_GLES31_CS_BD_TP_002, DEFAULT_TEST_RUN_TIME, "GLES31", "ComputeShader", "glBufferData")
TEST_PROCEDURE(GS_GLES31_CS_BD_TP_003, DEFAULT_TEST_RUN_TIME, "GLES31", "ComputeShader", "glBufferData")
TEST_PROCEDURE(GS_GLES31_CS_BD_TP_004, DEFAULT_TEST_RUN_TIME, "GLES31", "ComputeShader", "glBufferData")
